### ISSUE TITLE
Runtimes, memory given sample size, # variants

### ISSUE THREAD

**Issue by sdtemple** [alek0991/iSAFE#18]
I am trying to apply the iSAFE method; however, I find it eats up a lot of memory and runs slowly. Do you any comments with regards to # of samples and variants. For example, 10,000 phased diploids and 7k variants? I couldn't find any computational performance measurements in your paper. Thanks!

**Comment by sdtemple** [comment]
For reference, when I downsample to 100 phased diploids with 1.6k variants, it runs immediately and completes in seconds.

**Comment by alek0991** [comment]
The iSAFE software loads the entire genotype data for the specific region of interest. As a result, the memory consumption is  O(NM), where N is the the number of individuals and M is the the number of variants. The running time is O(NM^2). For more detail please check the following plots:

![mem](https://user-images.githubusercontent.com/11303721/221711503-fcc1da19-0734-4f4f-b409-be8542c5d1b3.png)
![time](https://user-images.githubusercontent.com/11303721/221711506-053ac8f8-f165-4803-a7ec-8b025ccfc335.png)

**Comment by alek0991** [comment]
The iSAFE software loads the entire genotype data for the specific region of interest. As a result, the memory consumption is O(NM), where N is the the number of individuals and M is the the number of variants. The running time is O(NM^2). For N=10,000 and M=7000, you will need ~6GB of RAM and ~17 minutes of a single core of a 2.60GHz CPU.

For more detail please check the following plots:

![mem](https://user-images.githubusercontent.com/11303721/221722099-2bfb1329-4a9b-49e0-980d-dd716153f1e6.png)
![time](https://user-images.githubusercontent.com/11303721/221722100-5b71bcc2-76c8-4895-a26f-acf75f7bc3b1.png)

**Comment by sdtemple** [comment]
Thank you for such a thorough response! Your ballpark estimates check out with what I observe. I found analysis with the whole dataset to be much more tractable once I left my local setup and accessed cluster resources.

Also, I appreciate how easy it is to get the program running. :)

**Comment by alek0991** [comment]
Great! I'm happy that you found the program easy to run :)
