### ISSUE TITLE
Functional effect whereby hap input "assumes... the selection is ongoing"?

### ISSUE THREAD

**Issue by lauterbur** [alek0991/iSAFE#2]
Hi,
I'm going to be using iSAFE on some .hap formatted, simulated data, and I'm wondering what the functional consequence is of the assumption that selection is ongoing when passing the --hap flag. I understand from the paper that iSAFE's power decreases when the favored allele frequency > 0.9, but what I'm really trying to figure out is if there is any affect on the iSAFE score as it is calculated (not its power) between .hap and .vcf formatted input. From what I can tell in the program, when given a hap file, it is essentially read in as a pandas dataframe as-is:
`snp_matrix = pd.read_csv(args.input, sep="\t", header=None, comment='#')`
whereas when given a vcf file, it checks if the derived allele frequency is > 0.9 and adds in the appropriate number of random haplotypes if so:
`Need_Random_Sample = sum((dfreq['case']>0.9)&(dfreq['MDDAF']>0.78))>0
...
if Need_Random_Sample | ForceRandomSample:
        case_num = sum(df.columns.get_level_values("group")=='case')
        NumberRandomSample = int(np.round(RandomSampleRate/(1-RandomSampleRate)*case_num))
        if status:
            print "Adding %i random haplotypes (%i%%)." % (NumberRandomSample, RandomSampleRate * 100)`

So is it basically the difference between the iSAFE program proactively fixing a potential lack of power issue for you (with vcf input) or not (with hap input)?

Thanks for your time.

**Comment by alek0991** [comment]
Hi,
hap mode:
As you mentioned, in the current implementation of iSAFE, the hap mode is not handling adding random samples. So if the selection is fixed or very close to fixation user must add random sample with the criteria we proposed in the _Adding outgroup samples_ from [online methods](https://www-nature-com.ezp-prod1.hul.harvard.edu/articles/nmeth.4606#methods). For more on this please see the [Input section](https://github.com/alek0991/iSAFE/blob/master/ReadMe.md#input) of the ReadMe.md file.

vcf mode: 
The software in vcf mode is more flexible and has more options. But if you don't have out-group samples (```--vcf-cont``` is not set), and hap file and vcf file contain the _exact_ same information (iSAFE only cares about position, phase, derived allele (1), and ancestral allele (0) in the vcf mode), then the output of iSAFE must be identical. In vcf mode, given proper outgroup populations (using ```--vcf-cont```and ```--sample-cont``` arguments) the program calculates Eq. 6 ([online methods](https://www.nature.com/articles/nmeth.4606#methods)) and automatically decides whether random samples are required or not. As an example see the [**Scenario 3 of the Demo 2**](https://github.com/alek0991/iSAFE#demo-2-input-in-vcf-format). 

Please let me know if you have any question.
Best,
Ali

**Comment by lauterbur** [comment]
Hi Ali,

Thank you, that clarifies what I was thinking. It's helpful to have spelled
out that the output will be identical from hap and vcf modes when there are
no outgroup samples.

Cheers,
Elise

**Comment by alek0991** [comment]
I'll definitely incorporate your suggestion. 
Thanks,
Ali
