### ISSUE TITLE
threshold value for selection

### ISSUE THREAD

**Issue by Kaaaaaai** [alek0991/iSAFE#3]
I want to determine if there is a selection by calculating the iSAFE value of all separation sites in an area. But how can I tell if the snp site is positively selected? 
Does the top 15 iSAFE score indicate that the site is positively selected? 
In paper you said that peak iSAFE score = 0.027 was a weak signal and could not make a prediction, is there any recommended threshold ?

I'm very grateful for any useful answers, thanks.

**Comment by alek0991** [comment]
Dear Kai,

iSAFE can be used as a test of selection and its power for detecting selection has been evaluated in the [Supp. Fig 29 of Sugden et al. 2018](https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-018-03100-7/MediaObjects/41467_2018_3100_MOESM1_ESM.pdf). However, the absolute value of iSAFE and SAFE depends on sample size, window size, population parameters like mutation rate, recombination rate, effective population size, and so on. 

For real data, I would recommend calculating iSAFE on other parts of the genome with the same iSAFE parameters and pick an empirical threshold. 

For simulation you can do similar by calculating iSAFE for many replicates with the same simulation and iSAFE parameters.

Please do not hesitate to contact me if you have any question. 
Best,
Ali

**Comment by Kaaaaaai** [comment]
Hi Ali,

Thank you very much for your suggestions.

As far as I understand, I should use some of the reported positively selected SNPs, calculate their iSAFE values using different parameters, count their ranking within a range to infer reasonable parameters.

But if I detect strong selective sweep signals in an area by Linkage Disequilibrium (LD) or Site Frequency Spectrum (SFS) methods , can I ignore the value and directly use the rank of iSAFE/SAFE in the region for the filtering of the favoured mutation? For example, the SNP site with the highest SAFE value has the greatest probability of a driver mutation.

Best,
Kai

**Comment by alek0991** [comment]
Sorry if my explanation was confusing. You should not pick reported positively selected SNPs.  You want to get a sense of iSAFE and peak-iSAFE distribution in your data. Following is one way you can do it:

1. Calculate iSAFE in your target region.
2. Calculate iSAFE on many other randomly selected regions with the same parameter used for iSAFE program in the target region. You can even cover the whole genome if you wish. This gives you a sense of iSAFE and peak-iSAFE distribution in your data.
3. If the value of peak-iSAFE is significant compared to the corresponding value for other regions then it can be a signal of selection and iSAFE ranking is reliable.

You can also simulate your population but this one is more work. For the European populations of the 1000GP, with a 5Mbp window size, we found iSAFE ranking is reliable when peak-iSAFE>0.1. Please check the [Supp. Figure 7 of the iSAFE paper.](https://www-nature-com.ezp-prod1.hul.harvard.edu/articles/nmeth.4606/figures/10). 

I don't recommend using iSAFE signal without having a sense of the significance of the iSAFE score even if other methods shows signal of selection. This signals can be a false positive. For example admixture and introgression can lead to spurious signal of selection.

**Comment by Kaaaaaai** [comment]
I'm confused about the simulation method in Figure7 in your supplement. In **(a)** you randomly produce 5000 random 5M length windows and divide the resulting window into two categories based on the peak iSAFE value. The discovery that favoured mutation ranks high in the peak iSAFE > 0.1 group indicates that the ranking is reliable in the case of peak iSAFE > 0.1. In Figure **(b)** you give the specific data in each simulation. Is my understanding correct?

My question is:
1.	How do you know which favoured mutation is in each simulation? Do you use the data you simulate yourself or the real population data? 

2.	How is the p-value specifically calculated in Figure b? 

3.	If my window is small and can only be compared using the SAFE value, is   it also possible to do simuation to determine a more reasonable peak SAFE threshold.

Thank you so much.

**Comment by alek0991** [comment]
Yes your understanding is correct. 
1- Yes I simulate it myself. For more details about simulations please see the section _Default simulation parameters_ in the online methods of the paper.
2- Please check the _Computing empirical P values_   in the online methods of the paper.
3- Yes you can do the same thing for SAFE. 

Please let me know if you have anymore question,
Best,
Ali

**Comment by Kaaaaaai** [comment]
Hi Ali,

I have encountered some cases where the SAFE value is inconsistent with other test results. For example, a region has a high iHS score but the peak safe value in this region is not high (relative to I randomly extracted 1000 regions of the same length). What is the reason for this situation? Is the peak safe value only used to measure the reliability of the ranking, and can not be used to accurately detect the selection signal?

Best,
Kai

**Comment by alek0991** [comment]
Hey Kai, 

There are many methods developed to detect regions under selection and one of the most effective one is iHS. However, SAFE score is the building block of the iSAFE and both SAFE and iSAFE where designed to pinpoint the favored mutation. In principle you can use them as a test of selection across the genome with proper normalization. If you want to use SAFE as a test of selection across the genome it must be normalized by frequency (like iHS). The SAFE score tends to have lower variance when the frequency of the favored allele is close to 1 or 0. Maybe the favored allele frequency for your target region is close to fixation and normalizing the SAFE score by frequency may resolve this discrepancy.

Best,
Ali

**Comment by Kaaaaaai** [comment]
I am not going to use SAFE/iSAFE to test selection across the genome. I just want use it to pinpoint 
where the favoured mutation is in some candidates selection region (detected by other methods) .

Now my strategy is as follows: 
Calculate the peak safe value of the candidate area, and randomly select some areas of the same length, and use the same parameters for calculation. If the peak safe value of the candidate region is significantly higher than the randomly selected background regions, then the few mutations with the highest value are selected as my candidate positive selection sites.

Is my idea reasonable? Another problem now is in some areas where the SNP site that is being selected to be nearly fixed, its peak SAFE/iSAFE value may not be high, so the ordering in this area is not reliable? Can it be solved by normalized SAFE/iSAFE scores in frequency bins across the entire genome?

**Comment by alek0991** [comment]
- Yes your approach is reasonable. 
- If you want to pinpoint the favored mutation you cannot normalize iSAFE/SAFE by frequency because it can completely change the ranking. For close to fixation sweeps you can add random samples from an out-group population as explained in the paper. 
Please let me know if you have anymore question.
Best,
Ali
