### ISSUE TITLE
using iSAFE without an ancestral allele file

### ISSUE THREAD

**Issue by js4u13** [alek0991/iSAFE#4]
Hello,
I have seen a few papers apply iSAFE to identify mutations in domestication selective sweeps in plants, and would really like to conduct this kind of analysis for my own work. For my project, I’ve mapped reads from individuals in two populations to the reference genome assembly for the species and then looked for signals of selective sweeps. From this I have a vcf file for each of the two populations mapped to the reference genome. I was hoping that I could use the vcf input format with the –sample-case and –sample-cont options with iSAFE, but I don’t have an ancestral allele file (as available for humans in the example given). The process for making an ancestral allele file looks very involved, so I’m wondering if I can still do the equivalent of this analysis by converting (and combining) my vcfs to hap files for input to iSAFE? If you have any thoughts on how best to approach this I’d be very grateful!
Many thanks,
Jasmine

**Comment by alek0991** [comment]
Hi Jasmine, 
I apologize for the late response. I have released a new version (v1.0.5) that handle vcf format without having AA-file. Please let me know if this works for you or if you encounter any issue.
Best,
Ali

**Comment by js4u13** [comment]
Hi Ali,
Thank you so much! I will give it a go and let you know how I get on.
Thanks again,
Jasmine
